name: Run Python Script

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 17:00 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetch latest code from repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Install Python 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install packages from requirements.txt

      - name: Run Python Script
        run: python main.py  # Execute main.py script

      - name: Commit Updated CSV Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet || git commit -m "Updated price data"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
